language: go

branches:
  only:
  - master

matrix:
  include:
    - name: "go1.13.x-linux"
      go: 1.13.x
      os: linux
      script: make test
    - name: "go1.14.x-linux"
      go: 1.14.x
      os: linux
      script: make travis-test
    - name: "go1.14.x-linux-static-check"
      go: 1.14.x
      os: linux
      before_script:
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.23.8
        - go get -u golang.org/x/lint/golint 
        - go get -u https://github.com/gordonklaus/ineffassign
      script:
        - make golangci-lint-check
        - make static-check
    - name: "go1.14.x-linux-arm64"
      go: 1.14.x
      os: linux
      arch: arm64
      dist: bionic
      script: GOPROXY=direct GOSUMDB=off DRAGONBOAT_MEMFS_TEST=1 make test
    - name: "go1.14.x-linux-race"
      go: 1.14.x
      os: linux
      script: RACE=1 make test
    - name: "go1.14.x-darwin"
      go: 1.14.x
      os: osx
      script: make test
    - name: "go1.14.x-windows"
      go: 1.14.x
      os: windows
      script: go test -v
    - name: "go1.14.x-freebsd"
      go: 1.14.x
      os: freebsd
      script: gmake test

notifications:
  recipients:
    - nilei81@gmail.com
  on_success: never
  on_failure: always

after_success:
  - bash <(curl -s https://codecov.io/bash)
