language: go
sudo: required

go:
  - 1.12.5
  - 1.11.4

notifications:
  on_success: never
  on_failure: never

before_install:
  - make install-rocksdb-ull
  - go get -u google.golang.org/grpc

script:
  - make ci-quick-test
  - go test -tags "dragonboat_leveldb_test" -v -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
