language: go

branches:
  only:
  - master

matrix:
  include:
    - name: "go1.13.x-linux"
      go: 1.13.x
      os: linux
      script: make travis-test
    - name: "go1.14.x-linux"
      go: 1.14.x
      os: linux
      script: make travis-test
    - name: "go1.14.x-darwin"
      go: 1.14.x
      os: osx
      script: make travis-test
    - name: "go1.14.x-windows"
      go: 1.14.x
      os: windows
      script: go build -v ./...
    - name: "go1.14.x-freebsd"
      go: 1.14.x
      os: linux
      script: GOOS=freebsd go build -v ./...

notifications:
  recipients:
    - nilei81@gmail.com
  on_success: never
  on_failure: always

after_success:
  - bash <(curl -s https://codecov.io/bash)
