on:
  schedule:
  - cron: '*/10 * * * *'
name: Nightly
jobs:
  monkey-test:
    runs-on: ubuntu-18.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - name: Test
      env:
        DRUMMER_NIGHTLY_PASSWORD: ${{ secrets.DRUMMER_NIGHTLY_PASSWORD }}
      run: |
        echo -e "machine github.com\n  login drummernightly\n password $DRUMMER_NIGHTLY_PASSWORD" > ~/.netrc
        git config --global credential.helper "netrc -d -v"
        git clone https://github.com/lni/drummer2 drummer
        cd drummer
        go get github.com/lni/dragonboat/v3@master
        make monkey-test
  ondisk-monkey-test:
    runs-on: ubuntu-18.04
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - name: Test
      env:
        DRUMMER_NIGHTLY_PASSWORD: ${{ secrets.DRUMMER_NIGHTLY_PASSWORD }}
      run: |
        echo -e "machine github.com\n  login drummernightly\n password $DRUMMER_NIGHTLY_PASSWORD" > ~/.netrc
        git config --global credential.helper "netrc -d -v"
        git clone https://github.com/lni/drummer2 drummer
        cd drummer
        go get github.com/lni/dragonboat/v3@master
        make ondisk-monkey-test
